[project]
name = "nix-debian"
version = "0.0.0"
description = "Build Debian packages from NIX"
authors = [ {name="Brian May", email="brian@linuxpenguins.xyz"}, ]
readme = "README.md"
dependencies = [
    "gbp == 0.9.32",]
requires-python = ">=3.9"
